name: Sync Fork

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure git for pushing
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/chatanywhere/GPT_API_free.git
          git fetch upstream

      - name: Checkout main branch
        run: git checkout main

      - name: Merge upstream changes
        run: |
          git merge upstream/main -m "Sync from upstream" || (echo "Merge conflict detected, aborting." && git merge --abort && exit 1)

      - name: Push changes if any
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
